In [9]:
import numpy as np
from classes.gaussian import Gaussian_mean
from classes.poisson import Poisson
from classes.multinomial import Multinomial
from methods.general import normArray, genDiscreteDist
import scipy.stats as stats
from scipy.special import gamma
import matplotlib.pyplot as plt

In [5]:
dist1 = genDiscreteDist()

dist2 = genDiscreteDist(i=10)

print(np.argmax([2, 1, 2, 4]))

print(dist1)
dist2

3
[[0.35589737 0.47790861 0.16619401]]


array([[0.31070487, 0.26323481, 0.42606031],
       [0.17319043, 0.38517769, 0.44163188],
       [0.62213782, 0.0958702 , 0.28199199],
       [0.39985633, 0.12298383, 0.47715984],
       [0.87226398, 0.01551819, 0.11221783],
       [0.58161062, 0.35478827, 0.06360111],
       [0.36241425, 0.39606714, 0.2415186 ],
       [0.71118783, 0.10235056, 0.18646161],
       [0.16646931, 0.4307149 , 0.40281579],
       [0.44558396, 0.37370022, 0.18071582]])

In [37]:
dist2 @ dist1.reshape((3, 1))

array([[0.3257589 ],
       [0.32462019],
       [0.32320992],
       [0.37569003],
       [0.36400564],
       [0.35171769],
       [0.31415187],
       [0.32931687],
       [0.36898525],
       [0.3112523 ]])

In [38]:
np.sum(dist2 * dist1, axis=1)

array([0.3257589 , 0.32462019, 0.32320992, 0.37569003, 0.36400564,
       0.35171769, 0.31415187, 0.32931687, 0.36898525, 0.3112523 ])

In [28]:
test = [
    np.array([0.2, 0.8]),
    np.array([0.1, 0.9]),
    np.array([0.4, 0.6])
]

arr = np.array(test)
arr
np.mean(arr, axis=0)

test = np.random.uniform(size=(10, 4))
col = 3*np.ones(10).astype(int)
print(col)
test[:,col] = 1
print(test)
idx = np.array([0, 2, 1, 2]).reshape((2, 2))
test[idx] = 1
test

[3 3 3 3 3 3 3 3 3 3]
[[0.36324563 0.63243167 0.07551305 1.        ]
 [0.06702994 0.84703706 0.40539196 1.        ]
 [0.70459768 0.77334949 0.37368799 1.        ]
 [0.08307951 0.19136392 0.77157682 1.        ]
 [0.03399684 0.48144141 0.69926226 1.        ]
 [0.30126824 0.20208247 0.93714238 1.        ]
 [0.93442907 0.2692157  0.36819633 1.        ]
 [0.27600457 0.43373612 0.39068591 1.        ]
 [0.00473802 0.63994244 0.88524736 1.        ]
 [0.25915064 0.11423422 0.46072754 1.        ]]


array([[1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [0.08307951, 0.19136392, 0.77157682, 1.        ],
       [0.03399684, 0.48144141, 0.69926226, 1.        ],
       [0.30126824, 0.20208247, 0.93714238, 1.        ],
       [0.93442907, 0.2692157 , 0.36819633, 1.        ],
       [0.27600457, 0.43373612, 0.39068591, 1.        ],
       [0.00473802, 0.63994244, 0.88524736, 1.        ],
       [0.25915064, 0.11423422, 0.46072754, 1.        ]])

In [9]:
c = 4
d = 6
data_m = np.array([2, 1, 0, 2, 1, 0]).reshape((d, 1))
print(data_m)

mult = Multinomial('multi', c, data=data_m, num_outcomes=3)

print(isinstance(data_m, np.ndarray))

mult.params[data_m.flatten(), :]


[[2]
 [1]
 [0]
 [2]
 [1]
 [0]]
True


array([[0.57177513, 0.17710017, 0.33629181, 0.26768731],
       [0.38255002, 0.45751597, 0.22249206, 0.34206496],
       [0.04567485, 0.36538386, 0.44121613, 0.39024773],
       [0.57177513, 0.17710017, 0.33629181, 0.26768731],
       [0.38255002, 0.45751597, 0.22249206, 0.34206496],
       [0.04567485, 0.36538386, 0.44121613, 0.39024773]])

In [12]:
mult.likelihood.sum(axis=1)
np.where(mult.likelihood > 0.5)

(array([0, 3], dtype=int64), array([0, 0], dtype=int64))

In [22]:
mult.params.sum(axis=0)

array([1., 1., 1., 1.])

In [23]:
lp = np.array([-2, -1, -0.2, -1])

lp * np.ones((10, 4))

array([[-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ]])

In [18]:
a = np.array([0.2, 0.3, 0.1, 0.2])
b = np.log(a)
b_norm = np.exp(b - np.sum(a))
print(a)
print(a / np.sum(a))
print(b)
print(b_norm)


[0.2 0.3 0.1 0.2]
[0.25  0.375 0.125 0.25 ]
[-1.60943791 -1.2039728  -2.30258509 -1.60943791]
[0.08986579 0.13479869 0.0449329  0.08986579]


In [19]:
data_m = np.array([2, 1, 0, 2]).reshape((4, 1))

c = 4 # Clusters
o = 3 # Outcomes

probs = np.random.uniform(size=(o, c))

probs = normArray(probs, axis=1)

likelihood = np.zeros((data_m.shape[0], c))
print(len(data_m))
print(probs)

for i in range(len(data_m)):
    likelihood[i,:] = probs[data_m[i], :]

print(likelihood)

lkh = probs[data_m, np.arange(0, c)]

print(lkh)

lkh[1] += np.array([1, 1, 1, 1])

lkh

4
[[0.202918   0.54289964 0.0138171  0.24036526]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.30277826 0.20078698 0.35904451 0.13739025]]
[[0.30277826 0.20078698 0.35904451 0.13739025]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.202918   0.54289964 0.0138171  0.24036526]
 [0.30277826 0.20078698 0.35904451 0.13739025]]
[[0.30277826 0.20078698 0.35904451 0.13739025]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.202918   0.54289964 0.0138171  0.24036526]
 [0.30277826 0.20078698 0.35904451 0.13739025]]


array([[0.30277826, 0.20078698, 0.35904451, 0.13739025],
       [1.121079  , 1.01871384, 1.16963117, 1.69057599],
       [0.202918  , 0.54289964, 0.0138171 , 0.24036526],
       [0.30277826, 0.20078698, 0.35904451, 0.13739025]])

In [20]:
mult = Multinomial('multi', 3, 3, data=data_m)

[[0.64323975 0.2825023  0.5253643 ]
 [0.06344625 0.35371314 0.11126613]
 [0.293314   0.36378456 0.36336956]]


In [21]:
data = np.array([2, 4, 1, 3, 5, 5]).reshape((6, 1))

params = np.array([3, 2, 1])


print(params)

np.sum(data*params, axis=0)

[3 2 1]


array([60, 40, 20])

In [22]:
norm = Gaussian_mean('norm', params, data)
pois = Poisson('poisson', 3, data, rates=params)

pois.params

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
norm.likelihood

In [ ]:
norm.log_likelihood

In [ ]:
norm.log_likelihood + np.log(1 / np.sqrt(2 * np.pi * norm.variance))

In [ ]:
stats.norm(params, np.sqrt(np.var(data))).pdf(data)

In [ ]:
stats.norm(params, np.sqrt(np.var(data))).logpdf(data)

In [ ]:
pois.likelihood

In [ ]:
stats.poisson(params).pmf(data)

In [ ]:
pois.log_likelihood - np.log(gamma(data + 1))

In [ ]:
stats.poisson(params).logpmf(data)

In [ ]:
isinstance(data_m, np.ndarray)
data_m

In [53]:
c = 4
o = 3
t = np.random.randint(c, size=10)
print(t)

means = np.array([10, 20, 15, 30])

print(means[t])
np.random.normal(t, 1)

[0 0 3 3 0 2 2 2 3 1]
[10 10 30 30 10 15 15 15 30 20]


array([ 0.81493901,  2.18448713,  1.2807168 ,  2.79738633,  0.29827818,
       -0.23825859,  3.09004956,  2.94042019,  3.764426  ,  0.26948499])

In [13]:
p = np.random.uniform(size=(c, o))
p = normArray(p)

#np.random.choice(o, size=10, p=p[t,:])

p[t,:]

NameError: name 'o' is not defined

In [19]:
np.exp(-np.inf)
np.log(0)

-inf

In [21]:
100**101

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000