In [2]:
import numpy as np
from classes.gaussian import Gaussian_mean
from classes.poisson import Poisson
from classes.multinomial import Multinomial
from methods.general import normArray
import scipy.stats as stats
from scipy.special import gamma

In [9]:
c = 4
d = 6
data_m = np.array([2, 1, 0, 2, 1, 0]).reshape((d, 1))
print(data_m)

mult = Multinomial('multi', c, data=data_m, num_outcomes=3)

print(isinstance(data_m, np.ndarray))

mult.params[data_m.flatten(), :]


[[2]
 [1]
 [0]
 [2]
 [1]
 [0]]
True


array([[0.57177513, 0.17710017, 0.33629181, 0.26768731],
       [0.38255002, 0.45751597, 0.22249206, 0.34206496],
       [0.04567485, 0.36538386, 0.44121613, 0.39024773],
       [0.57177513, 0.17710017, 0.33629181, 0.26768731],
       [0.38255002, 0.45751597, 0.22249206, 0.34206496],
       [0.04567485, 0.36538386, 0.44121613, 0.39024773]])

In [12]:
mult.likelihood.sum(axis=1)
np.where(mult.likelihood > 0.5)

(array([0, 3], dtype=int64), array([0, 0], dtype=int64))

In [22]:
mult.params.sum(axis=0)

array([1., 1., 1., 1.])

In [23]:
lp = np.array([-2, -1, -0.2, -1])

lp * np.ones((10, 4))

array([[-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ],
       [-2. , -1. , -0.2, -1. ]])

In [18]:
a = np.array([0.2, 0.3, 0.1, 0.2])
b = np.log(a)
b_norm = np.exp(b - np.sum(a))
print(a)
print(a / np.sum(a))
print(b)
print(b_norm)


[0.2 0.3 0.1 0.2]
[0.25  0.375 0.125 0.25 ]
[-1.60943791 -1.2039728  -2.30258509 -1.60943791]
[0.08986579 0.13479869 0.0449329  0.08986579]


In [19]:
data_m = np.array([2, 1, 0, 2]).reshape((4, 1))

c = 4 # Clusters
o = 3 # Outcomes

probs = np.random.uniform(size=(o, c))

probs = normArray(probs, axis=1)

likelihood = np.zeros((data_m.shape[0], c))
print(len(data_m))
print(probs)

for i in range(len(data_m)):
    likelihood[i,:] = probs[data_m[i], :]

print(likelihood)

lkh = probs[data_m, np.arange(0, c)]

print(lkh)

lkh[1] += np.array([1, 1, 1, 1])

lkh

4
[[0.202918   0.54289964 0.0138171  0.24036526]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.30277826 0.20078698 0.35904451 0.13739025]]
[[0.30277826 0.20078698 0.35904451 0.13739025]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.202918   0.54289964 0.0138171  0.24036526]
 [0.30277826 0.20078698 0.35904451 0.13739025]]
[[0.30277826 0.20078698 0.35904451 0.13739025]
 [0.121079   0.01871384 0.16963117 0.69057599]
 [0.202918   0.54289964 0.0138171  0.24036526]
 [0.30277826 0.20078698 0.35904451 0.13739025]]


array([[0.30277826, 0.20078698, 0.35904451, 0.13739025],
       [1.121079  , 1.01871384, 1.16963117, 1.69057599],
       [0.202918  , 0.54289964, 0.0138171 , 0.24036526],
       [0.30277826, 0.20078698, 0.35904451, 0.13739025]])

In [20]:
mult = Multinomial('multi', 3, 3, data=data_m)

[[0.64323975 0.2825023  0.5253643 ]
 [0.06344625 0.35371314 0.11126613]
 [0.293314   0.36378456 0.36336956]]


In [21]:
data = np.array([2, 4, 1, 3, 5, 5]).reshape((6, 1))

params = np.array([3, 2, 1])


print(params)

np.sum(data*params, axis=0)

[3 2 1]


array([60, 40, 20])

In [22]:
norm = Gaussian_mean('norm', params, data)
pois = Poisson('poisson', 3, data, rates=params)

pois.params

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
norm.likelihood

In [ ]:
norm.log_likelihood

In [ ]:
norm.log_likelihood + np.log(1 / np.sqrt(2 * np.pi * norm.variance))

In [ ]:
stats.norm(params, np.sqrt(np.var(data))).pdf(data)

In [ ]:
stats.norm(params, np.sqrt(np.var(data))).logpdf(data)

In [ ]:
pois.likelihood

In [ ]:
stats.poisson(params).pmf(data)

In [ ]:
pois.log_likelihood - np.log(gamma(data + 1))

In [ ]:
stats.poisson(params).logpmf(data)

In [ ]:
isinstance(data_m, np.ndarray)
data_m

In [53]:
c = 4
o = 3
t = np.random.randint(c, size=10)
print(t)

means = np.array([10, 20, 15, 30])

print(means[t])
np.random.normal(t, 1)

[0 0 3 3 0 2 2 2 3 1]
[10 10 30 30 10 15 15 15 30 20]


array([ 0.81493901,  2.18448713,  1.2807168 ,  2.79738633,  0.29827818,
       -0.23825859,  3.09004956,  2.94042019,  3.764426  ,  0.26948499])

In [64]:
p = np.random.uniform(size=(c, o))
p = normArray(p)

#np.random.choice(o, size=10, p=p[t,:])

p[t,:]

array([[0.08312119, 0.47187495, 0.44500385],
       [0.08312119, 0.47187495, 0.44500385],
       [0.42371954, 0.41175504, 0.16452542],
       [0.42371954, 0.41175504, 0.16452542],
       [0.08312119, 0.47187495, 0.44500385],
       [0.26853605, 0.30268066, 0.42878329],
       [0.26853605, 0.30268066, 0.42878329],
       [0.26853605, 0.30268066, 0.42878329],
       [0.42371954, 0.41175504, 0.16452542],
       [0.50349964, 0.35689566, 0.13960469]])